title: Cherifi Youssouf
logo: "/images/Profile.png?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello, World!
  <br><br>
  <br><br>
  
  <a href="https://www.linkedin.com/in/youssouf-ismail-cherifi-81a09777/">LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
